// Mocks generated by Mockito 5.2.0 from annotations
// in azkar/test/main_module/presentation/bloc/prayer_timing_bloc_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i5;

import 'package:azkar/main_module/data/failures.dart' as _i6;
import 'package:azkar/main_module/data/repositories/prayer_timing_repository.dart'
    as _i2;
import 'package:azkar/main_module/domain/entities/prayer_timing_entity/prayer_timing_entity.dart'
    as _i7;
import 'package:azkar/main_module/domain/usecases/get_prayer_timings.dart'
    as _i4;
import 'package:either_dart/either.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

class _FakePrayerTimingsRepository_0 extends _i1.Fake
    implements _i2.PrayerTimingsRepository {}

class _FakeEither_1<L, R> extends _i1.Fake implements _i3.Either<L, R> {}

/// A class which mocks [GetPrayerTimings].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetPrayerTimings extends _i1.Mock implements _i4.GetPrayerTimings {
  MockGetPrayerTimings() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.PrayerTimingsRepository get repo =>
      (super.noSuchMethod(Invocation.getter(#repo),
              returnValue: _FakePrayerTimingsRepository_0())
          as _i2.PrayerTimingsRepository);
  @override
  _i5.Future<_i3.Either<_i6.Failure, _i7.PrayerTimingEntity>> execute(
          String? lat, String? lng) =>
      (super.noSuchMethod(Invocation.method(#execute, [lat, lng]),
              returnValue:
                  Future<_i3.Either<_i6.Failure, _i7.PrayerTimingEntity>>.value(
                      _FakeEither_1<_i6.Failure, _i7.PrayerTimingEntity>()))
          as _i5.Future<_i3.Either<_i6.Failure, _i7.PrayerTimingEntity>>);
}
